refactor: cleanups
HiddenDevs/discord-prompts.js pull request #3
Opened 2023-11-26 14:24 UTC by xMooddyy

2023-11-27 22:43 UTC, xMooddyy commented
Just pushed a fix to the following error:

Whenever creating a modal button/select menu, if the user opens the modal and closes it, the whole interaction fails and they cannot click any button anymore. 

The fix:

Revert back to using `.createMessageComponentCollector`, this allows the user to still click buttons even after opening and closing a modal.

2023-11-28 22:02 UTC, sm3136 requested changes
I would try to make some changes that revolve around those comments. I think one of them has a potential to improve speed, others are kind of just nit picks.

2023-11-28 22:02 UTC, sm3136 commented on examples/simple-marketplace/states/InitialState.ts
> +						ctx.previousState = [initialState.name];
Handled by the prompt system on its own, shouldn't need to do this anymore.

2023-11-28 22:02 UTC, sm3136 commented on examples/simple-marketplace/states/preCreatePostState.ts
> +						ctx.previousState.push(preCreatePostState.name);
Handled by the prompt system on its own, shouldn't need to do this anymore.

2023-11-29 19:40 UTC, merged